Feature/constrain available blocks
dxw/govuk-blogs pull request #221
Opened 2024-04-19 12:19 UTC by sbrody

Limits the blocks available to the editor to those listed here: https://trello.com/c/T2J24OZI/11-confirm-supported-components

Unused blocks are left commented out so they can be easily reintroduced and as a reference.

2024-04-19 13:32 UTC, matthewpassmore requested changes
This constrains the vast amount of blocks, as expected 👍 

We also need to constrain the _Embed_ block variations to just YouTube and Vimeo. Currently there's a whole host of selections e.g. Spotify. You may need a slightly different approach for these. For example, [this is how we did it on NAO](feature/constrain-available-blocks), but there may be a PHP approach that compliments what you've done in this class.

2024-04-19 14:07 UTC, sbrody commented
> This constrains the vast amount of blocks, as expected 👍
> 
> We also need to constrain the _Embed_ block variations to just YouTube and Vimeo. Currently there's a whole host of selections e.g. Spotify. You may need a slightly different approach for these. For example, [this is how we did it on NAO](feature/constrain-available-blocks), but there may be a PHP approach that compliments what you've done in this class.

Good point - have done that in JS as it fits with the approach we've taken to block variations

2024-04-19 15:43 UTC, matthewpassmore requested changes

2024-04-19 15:43 UTC, matthewpassmore commented on app/Blocks/AllowedBlocks.php
> +				// 'core/shortcode',
This needs to be enabled, to allow continued use of the _Footnotes_ shortcode, if they prefer the existing workflow to the native block.

2024-04-22 09:43 UTC, matthewpassmore approved these changes
Looks good to me 👍

2024-04-22 09:47 UTC, merged