Don't display a byline if the page has an invalid author
dxw/govuk-blogs pull request #270
Opened 2024-12-12 17:18 UTC by leedxw

Posts having post_author ids that refer to deleted users cause problems - even if co-authors is populated.

In the short term, don't attempt to resolve the author, and independently find posts with

a) deleted authors
b) populated co-authors

and switch them to be user 0

2024-12-13 10:08 UTC, RobjS commented
@leedxw Is there a known way to recreate the issue this fixes? Without this fix, I've tried authoring a post, and then removing the post author from the database entirely, but the page still renders just with an empty author. I do see a PHP warning in the logs:

```
PHP Warning:  Attempt to read property "user_login" on bool in /var/www/html/wp-content/plugins/co-authors-plus/template-tags.php on line 129
```

Is the intention of this fix to address that warning?

2024-12-13 12:29 UTC, leedxw commented
It addresses this warning, but you'll also see a perpetual spinner under "Authors" if you edit the page.

2024-12-13 12:30 UTC, leedxw commented
(I suspect there are other issues related to posts that have owners for which lookups fail.)

2024-12-13 12:33 UTC, leedxw commented
Note that we shouldn't apply this to production until we have reassigned the existing deleted-author posts to an existing author. This output is intended to explain future issues from deleted users.

2024-12-13 17:31 UTC, RobjS commented on templates/entry-meta.php
> +		add_filter('wp_insert_post_data', 'set_archive_author', '99', 2);
Generally the priority is expected to be an int rather than a string: https://developer.wordpress.org/reference/functions/add_filter/

2024-12-13 17:35 UTC, RobjS commented on lib/set-archive-author.php
> +	$data['post_author'] = 2;
I'm unsure about tightly coupling the database state to the code like this. If we're running this in a context where the user with ID 2 is a legitimate user, or if that user also gets deleted it feels like this could come back to bite us.

2024-12-16 08:14 UTC, snim2 requested changes
See Rob's comments

2024-12-18 10:34 UTC, leedxw commented on lib/set-archive-author.php
> +	$data['post_author'] = 2;
I've removed the hardcoded uid and instead do a lookup `get_option('archive_author')`

2025-01-02 15:05 UTC, RobjS requested changes
I think this is generally a good approach (i.e. relying on the option value), but I don't think the current implementation will do anything to amend the missing author data, based on my testing and reading of the code.

We're hooking into the `wp_insert_post_data` hook in the `entry-meta.php` partial, but that only loads in the front end. So over the course of the request that loads that partial, `wp_insert_post()` will never be called, so `set_archive_author()` won't kick in.

So we probably want to do something like call (with additional checks etc. not shown here):
```php
wp_update_post([
  'ID' => 123, /* The ID of the post in question */
  'post_author' => get_option('archive_author')
]);
```

directly when we are rendering a post that references a missing author, as any hooks that will only fire when the post is updated are never going to be called in the course of rendering the post in the front-end.

2025-01-02 15:05 UTC, RobjS commented on templates/entry-meta.php
> +		add_filter('wp_insert_post_data', 'set_archive_author', 99, 2);
I don't think this is going to do anything, because we're adding this filter when rendering the page in the front end, but the hook will only be fired if `wp_insert_post()` is called, and that's not going to happen over the remaining course of the request that loads this partial.

2025-01-02 15:21 UTC, leedxw commented on templates/entry-meta.php
> +		add_filter('wp_insert_post_data', 'set_archive_author', 99, 2);
My first pass at testing was just to confirm if the change avoids the lookup error rather than changing the database.

2025-01-02 15:29 UTC, RobjS commented on templates/entry-meta.php
> +		add_filter('wp_insert_post_data', 'set_archive_author', 99, 2);
It'd need to be a hook that fires in the course of rendering a front-end page, but after this, e.g. `wp_footer` or something along those lines.

2025-01-06 10:18 UTC, RobjS commented
I'm a bit confused on what we're trying to achieve here now. Is the intention just to log the places where this is an issue, or fix the issue in the db? If we're trying to fix the issue in the db when the post is rendered in the front-end, that'll only work if we call `wp_update_post()` or similar ourselves, in the process of rendering the page.

2025-01-07 17:38 UTC, RobjS requested changes
I think there's a couple of bugs here that are stopping this having its intended effect.

2025-01-07 17:38 UTC, RobjS commented on lib/set-archive-author.php
> +	$archive_username = get_option('archive_author');
Bug: it looks like this should be `$archive_author = get_option('archive_author');`. The `$archive_username` variable isn't used again here.

2025-01-07 17:38 UTC, RobjS commented on lib/set-archive-author.php
> +			$archive_author_id = get_user_by('id', $archive_author);
Bug: `get_user_by` returns a `WP_User` object. If we're assuming that the `archive_author` option value will always be an integer, even if it's returned as a string, do we need to do anything here other than maybe convert it to the integer type? e.g.

`$archive_author_id = intval($archive_author)`

`get_option` will often return a string even if the value in the database is an integer, so we can't assume that the fact the `is_int()` test has failed indicates that we should assume the value is a text string, rather than an integer in string format.

2025-01-09 17:12 UTC, RobjS commented
Superseded by #275

2025-01-09 17:12 UTC, closed without merging